version: "3"
networks:
  expense:
volumes:
  mysql: #Docker Volume Create Mysql
services:
  mysql:
    image: rajeshvalluri11/mysql:v1
    container_name: mysql # --name mysql
    volumes:
    - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql
  backend:
    image: rajeshvalluri11/backend:v1
    container_name: backend
    depends_on:
    - mysql
  frontend:
    image: rajeshvalluri11/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend

